### ISSUE TITLE
1inch issue signing

### ISSUE THREAD

**Issue by anxolin** [gnosis/cowswap#700]
**Describe the bug**
Wrapping ETH and approving WETH worked.

Failed when I tried to sign.

**How to Reproduce**
To reproduce, install 1inch app, and connect using wallet connect. Tested in IOS

When signing:
![image](https://user-images.githubusercontent.com/2352112/119880444-8c67a100-bf2c-11eb-9582-473f4dee9157.png)

**Comment by alfetopito** [comment]
iOS only wallet
Probably we could make it use a different signing method if we can find out which error exactly it returns
Disabling it for now on #701

**Comment by anxolin** [comment]
@alfetopito In this case, we are getting an error back from the wallet. In this case, shouldn't this be triggering the fallback logic?

**Comment by anxolin** [comment]
Debugged this a bit more, because I suspected that maybe the error was in WC library handling the error, but we are seeing the original error sent by 1inch:

![image](https://user-images.githubusercontent.com/2352112/120189379-8ff27500-c217-11eb-80c5-58691443cf18.png)

**Comment by anxolin** [comment]
I tried with v4, v3, ethsign, and same result for all of them. Just leaving this issue open and deprioritizing.

I contacted 1inch through their chat, to notify them about the issue, plus created this PR to leave it open for wallets to try to debug the errors #718 (since main branches have the wallets disabled)

**Comment by anxolin** [comment]
UPDATE: The support team says that they solved this, now they implement EIP-712 but still needs to pass QA and deploy to production (needs apple signature)

**Comment by alfetopito** [comment]
@anxolin I think this is fixed, right?

**Comment by anxolin** [comment]
Not in IOS....

**Comment by elena-zh** [comment]
Hey @anxolin , the issue is still relevant in v 1.5.0: I can wrap/unwrap tokens using 1Inch wallet, but I can't sign an order. 
https://watch.screencastify.com/v/x6O8F5nCmPi4VPwLE2WW

**Comment by elena-zh** [comment]
In a mobile view I can't even wrap/unwrap:  I can't see confirmation modal in the connected wallet:

https://user-images.githubusercontent.com/70885163/143583067-0c25a289-f13e-4511-998a-c79170bf651a.mp4

**Comment by podkovyrin** [comment]
@elena-zh you just need to tap the Hide button in the top left. Though I agree that might be not clear. We will improve UX here, thanks.

**Comment by elena-zh** [comment]
@podkovyrin , yes, thank you. I understood it in a while,.
Then, I was able to run some transactions. 

Thanks!

**Comment by anxolin** [comment]
Okay, nice so u were able to complete all the workflows with 1inch? 

Then we should re-enable it in production, although it would be good to make it more obvious how to close it as @podkovyrin pointed out.

**Comment by elena-zh** [comment]
Hey @anxolin , not exactly: 
1. I was able to run all flows using 1Inch integrated browser
2. When connected to the wallet using WC, I was able to wrap/unwrap/approve a token, but not to sign a Buy/Sell order.
I mentioned it here https://github.com/gnosis/cowswap/issues/700#issuecomment-979950976 .

**Comment by elena-zh** [comment]
1Inch wallet works as expected and has been enabled in v1.6.0
