### ISSUE TITLE
From field is filled in with 0 when press on the Max button for ETH/XDAI token with balance is < 0.01

### ISSUE THREAD

**Issue by elena-zh** [gnosis/cowswap#934]
1. Select ETH/XDAI  token in the 'From' field when its amount in a connected wallet is <0.01
2. Press on the 'Max' button

**Actual Result:** field's value = 0
https://drive.google.com/file/d/1RlM8Tan-i3eVdrLnJOMx4596PsfpEvOJ/view
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/a94245ea-55ee-4cf8-b530-ac40425df982)

**Expected Result:** field's value = token's max balance

**Comment by alfetopito** [comment]
Rounding issue hopefully fixed in `develop`/next release with formatSmart changes

cc @W3stside

**Comment by elena-zh** [comment]
I have updated the issue description as the previous issue is no longer reproducible in v.0.17, however, another issue with small amounts appeared during retesting the ticket.

**Comment by elena-zh** [comment]
The issue is still reproducible
![image](https://user-images.githubusercontent.com/70885163/141444758-3f53fca8-d599-46cb-a18c-e7157097add8.png)
